In [3]:
#импорт библиотеки
import numpy as np

Задание 1.

In [12]:
# Создаем 3 матрицы по условию ДЗ.
matrix_A = np.matrix([[1, 2, 1], [-2, 1, 1]])
matrix_B = np.matrix([[3,1], [-1, 0], [2, 4]])
matrix_C = np.matrix([[-2, 2], [1, -1], [1, 2]])

In [13]:
# Транспонируем матрицу А, т.к. сложение разномерных матриц не возможно.
matrix_A = np.transpose(matrix_A)
print(matrix_A)

[[ 1 -2]
 [ 2  1]
 [ 1  1]]


In [20]:
# Теперь можно выполнять вычисления по задаче. Результаты выводим на экран.
result1 = matrix_A + 2 * matrix_B
print(result1, end = "\n\n")
result2 = matrix_B + 2 * matrix_C
print(result2)

[[7 0]
 [0 1]
 [5 9]]

[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задание 2.

In [2]:
# Создаем матрицу 8х8 со значениями согласно заданию и выводим
matrix_zeros = np.zeros((8, 8))
matrix_zeros[0::2, 1::2] = 1
matrix_zeros[1::2, 0::2] = 1
print(matrix_zeros)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задание 3.

In [3]:
#создание 2х векторов
vect1 = np.arange(1.5, step = 0.1)
vect2 = np.arange(1, 7)

In [4]:
#преобразовываем векторы в матрицы и выводим их на экран
matrix_vect1 = vect1.reshape(5, 3)
print(matrix_vect1)
matrix_vect2 = vect2.reshape(3, 2)
print(matrix_vect2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
#перемножаем матрицы выводим результат
result = np.matmul(matrix_vect1, matrix_vect2)
print(result)

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Задание 4.

In [25]:
# Создаем вектор размерностью 36 типа int32 c порядком 1, 3, 5, 7 и тд.
vector = np.arange(1, 37, dtype = 'int32')
vector_odd = vector[(vector % 2 == 1)]

In [31]:
# Оставляем в нашем векторе только числа кратные 3 и выводим результат через запятую.
result = vector_odd[(vector_odd % 3 == 0)]
print(f"Исходный вектор: {vector_odd}")
print(f"Элементы кратные трём: {result}")

Исходный вектор: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]
Элементы кратные трём: [ 3  9 15 21 27 33]
